### ISSUE TITLE
Przygotowanie schematu bazy danych w oparciu o znalezione dotychczas dane i spotkanie pierwsze

### ISSUE THREAD

**Issue by kacperros** [Kolo-Naukowe-Data-Science-PW/wyniki-sportowe#17]

**Comment by kacperros** [comment]
Wszystkie encje powiązane z sezonową statystyką zrzucić do jednej giga-encji.

**Comment by smudap** [comment]
Rozumiem, że to gdzieś u siebie na komputerze robisz i nie widać tego na Githubie?
@kacperros

**Comment by smudap** [comment]
Nieważne. Zatwierdzam
