### ISSUE TITLE
Napisać funkcje ułatwiające umieszczanie danych w bazie, tak aby ukryć SQLową implementację.

### ISSUE THREAD

**Issue by kacperros** [Kolo-Naukowe-Data-Science-PW/wyniki-sportowe#20]

**Comment by SimplifyAll** [comment]
Podczas tworzenia tabeli team_season_statistics występuje błąd związany z niezgodnością kluczy.  Wcześniej hulało ale po zmianach w tabelach  gdzieś musiał wkraść się błąd
